#================configs related to carbon.xml=============
[server]
hostname = "IS_HOSTNAME"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
serverDetails = "WSO2 IS as KM 5.11.0"
mode = "single"
userAgent = "WSO2 IS as KM 5.11.0"
offset = 3

[keystore.primary]
name = "wso2carbon.jks"
password = "wso2carbon"

[tenant_mgt]
enable_email_domain = true

#================configs related to user-mgt.xml=============

[super_admin]
username = "admin@wso2.com"
password = "wso2123"
create_admin_account = true

[realm_manager]
data_source= "WSO2USER_DB"

[user_store]
type = "database_unique_id"
class = "org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager"

[user_store.properties]
UsernameJavaRegEx = "a-zA-Z0-9@._-{3,30}$"
UsernameJavaScriptRegEx = "^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$"
SCIMEnabled = false
IsBulkImportSupported = false
LeadingOrTrailingSpaceAllowedInUserName = false
UsernameWithEmailJavaScriptRegEx = "^[\\S]{3,30}$"

[authorization_manager]
class = "org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager"

[authorization_manager.properties]
AdminRoleManagementPermissions = "/permission"
AuthorizationCacheEnabled = true
GetAllRolesOfUserEnabled = false

#================configs related to master-datasources.xml=============

# for registry data
[database.shared_db]
url = "DB_GOV_URL"
username = "DB_USER"
password = "DB_PASS"
driver = "DB_DRIVER"

[database.shared_db.pool_options]
maxActive = "150"
maxWait = "60000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
validationInterval="30000"
defaultAutoCommit=false

# for api manager data
[database.identity_db]
url = "DB_APIMGT_URL"
username = "DB_USER"
password = "DB_PASS"
driver = "DB_DRIVER"

[database.identity_db.pool_options]
maxActive = "150"
maxWait = "60000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
validationInterval="30000"
defaultAutoCommit=false

# for km-config registry
[database.config]
url = "DB_IS_CONFIG_URL"
username = "DB_USER"
password = "DB_PASS"
driver = "DB_DRIVER"

[database.config.pool_options]
maxActive = "150"
maxWait = "60000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
validationInterval="30000"
defaultAutoCommit=false

# for user-mgt data
[database.user]
url = "DB_USER_STORE_URL"
username = "DB_USER"
password = "DB_PASS"
driver = "DB_DRIVER"

[database.user.pool_options]
maxActive = "150"
maxWait = "60000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
validationInterval="30000"
defaultAutoCommit=false

# for Open Banking  data
[[datasource]]
id="WSO2OB_DB"
url = "DB_OB_STORE_URL"
username = "DB_USER"
password = "DB_PASS"
driver = "DB_DRIVER"
jmx_enable=false
pool_options.maxActive = "150"
pool_options.maxWait = "60000"
pool_options.minIdle = "5"
pool_options.testOnBorrow = true
pool_options.validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
pool_options.validationInterval="30000"
pool_options.defaultAutoCommit=false

#================configs related to application-authentication.xml=============

[authentication.endpoints]
login_url = "https://IS_HOSTNAME:9446/authenticationendpoint/login.do"
retry_url = "https://IS_HOSTNAME:9446/authenticationendpoint/retry.do"

[authentication.endpoint.redirect_params]
filter_policy = "include"
remove_on_consume_from_api = "true"
parameters = ["sessionDataKeyConsent","relyingParty", "authenticators", "authFailureMsg", "authFailure"]

[authentication.authenticator.sms_otp.parameters]
EnableAccountLockingForFailedAttempts = true
BackupCode = false
TokenExpiryTime = 60

[[authentication.custom_authenticator]]
name = "IdentifierExecutor"
parameters.ValidateUsername = true
parameters.throttleLimit = 3
parameters.throttleTimePeriod = 300
parameters.authRequestURL = "https://IS_HOSTNAME:9446/api/identity/auth/v1.1/data/AuthRequestKey/"


#================configs related to identity.xml=============

[identity_data_source]
skip_db_schema_creation = true

[oauth]
allowed_scopes = ["OB.*", "profile"]

[oauth.token_renewal]
renew_refresh_token = false

[oauth.endpoints]
oauth2_consent_page = "${carbon.protocol}://IS_HOSTNAME:${carbon.management.port}/ob/authenticationendpoint/oauth2_authz.do"
oidc_consent_page = "${carbon.protocol}://IS_HOSTNAME:${carbon.management.port}/ob/authenticationendpoint/oauth2_consent.do"

[oauth.response_type]
token.enable = true
code.enable = false
id_token.enable = true
id_token_token.enable = false
device.enable = true

[[oauth.custom_response_type]]
name = "code"
class = "com.wso2.openbanking.accelerator.identity.auth.extensions.response.handler.OBCodeResponseTypeHandlerExtension"

[[oauth.custom_response_type]]
name = "code id_token"
class = "com.wso2.openbanking.accelerator.identity.auth.extensions.response.handler.OBHybridResponseTypeHandlerExtension"

[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1

[event_listener.properties]
PreventTokenReuse= false
RejectBeforeInMinutes= "100"
TokenEndpointAlias= "https://IS_HOSTNAME:9446/oauth2/token"
notification_endpoint = "https://APIM_HOSTNAME:9443/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "WSO2-IS"

[[event_listener]]
id = "private_key_jwt_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt.PrivateKeyJWTClientAuthenticator"
order = "899"


[oauth.grant_type]
iwa_ntlm.enable = false
jwt_bearer.enable = true

[identity_mgt.user_self_registration]
allow_self_registration = true

[[resource.access_control]]
context = "(.)/keymanager-operations/user-info/claims(.)"
secure = true
http_method = "GET"
permissions = "/permission/admin/manage/identity/usermgt/list"
scopes = "internal_user_mgt_list"

[[resource.access_control]]
context = "(.*)/keymanager-operations/user-info/claims/generate"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/usermgt/list"
scopes = "internal_user_mgt_list"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/create"
scopes = "internal_application_mgt_create"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "GET"
permissions = "/permission/admin/manage/identity/applicationmgt/view"
scopes = "internal_application_mgt_view"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "DELETE"
permissions = "/permission/admin/manage/identity/applicationmgt/delete"
scopes = "internal_application_mgt_delete"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "PUT"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

[[resource.access_control]]
context = "(.)/keymanager-operations/dcr/register(.)"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

[[resource.access_control]]
context = "(.*)/openbanking/dynamic-client-registration/(.*)"
secure="true"
http_method="all"
permissions=["/permission/admin"]
allowed_auth_handlers = ["BasicAuthentication"]

[[resource.access_control]]
context = "(.*)/api/openbanking/consent/(.*)"
secure="true"
http_method="all"
permissions=["/permission/admin"]
allowed_auth_handlers = ["BasicAuthentication"]

[[resource.access_control]]
context = "(.*)/consentmgr(.*)"
secure="false"
http_method="GET"

[[resource.access_control]]
context = "(.*)/api/openbanking/application/(.*)"
secure="false"
http_method="GET"

[authentication.adaptive.event_publisher]
url = "http://IS_HOSTNAME:8006/"

[tenant_context.rewrite]
custom_webapps = ["/keymanager-operations/"]

[oauth.mutualtls]
client_certificate_header = "x-wso2-mutual-auth-cert"

[event.default_listener.mutual_tls_authenticator]
enable = false

[[event_listener]]
id = "ob_mutual_tls_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.openbanking.accelerator.identity.clientauth.OBMutualTLSClientAuthenticator"
order = "26"
enable = true

[oauth.token.validation]
include_validation_context_as_jwt_in_reponse = "true"
validation_response_signing_algorithm = "SHA256withRSA"
validation_response_jwt_validity = "15m"

[oauth.extensions]
token_context_generator = "org.wso2.carbon.identity.oauth2.authcontext.JWTTokenGenerator"
token_context_claim_retriever = "org.wso2.carbon.identity.oauth2.authcontext.DefaultClaimsRetriever"
token_context_dialect_uri = "http://wso2.org/claims"

[oauth.token_generation]
access_token_type = "self_contained"

[oauth.grant_type.uma_ticket]
retrieve_uma_permission_info_through_introspection = true

[oauth.grant_type.refresh_token]
enable=true
grant_handler="com.wso2.openbanking.accelerator.identity.grant.type.handlers.OBRefreshGrantHandler"

[oauth.grant_type.authorization_code]
enable=true
grant_handler="com.wso2.openbanking.accelerator.identity.grant.type.handlers.OBAuthorizationCodeGrantHandler"

[oauth.grant_type.password]
enable=true
grant_handler="com.wso2.openbanking.accelerator.identity.grant.type.handlers.OBPasswordGrantHandler"

[oauth.grant_type.client_credentials]
enable=true
grant_handler="com.wso2.openbanking.accelerator.identity.grant.type.handlers.OBClientCredentialsGrantHandler"

[oauth.oidc.extensions]
claim_callback_handler="com.wso2.openbanking.accelerator.identity.claims.OBDefaultOIDCClaimsCallbackHandler"
request_object_validator = "com.wso2.openbanking.accelerator.identity.auth.extensions.request.validator.OBRequestObjectValidationExtension"
id_token_builder = "com.wso2.openbanking.accelerator.identity.idtoken.OBIDTokenBuilder"

#================configs related to identity-event.properties=============

[[event_handler]]
name="userPostSelfRegistration"
subscriptions=["POST_ADD_USER"]

#================configs related to open-banking.xml=============

[open_banking]
username="$ref{super_admin.username}"
password="$ref{super_admin.password}"

[[open_banking.jdbc_persistence_manager]]
data_source.name = "WSO2OB_DB"
connection_verification_timeout=1

#=======================dcr configs======================
[open_banking.dcr]
validator = "com.wso2.openbanking.cds.identity.dcr.validation.CDSRegistrationValidatorImpl"
jwks_url_sandbox = "https://keystore.openbankingtest.org.uk/0015800001HQQrZAAX/9b5usDpbNtmxDcTzs7GzKp.jwks"
jwks_url_production = "https://keystore.openbankingtest.org.uk/0015800001HQQrZAAX/9b5usDpbNtmxDcTzs7GzKp.jwks"
applicationupdater = "com.wso2.openbanking.cds.identity.listener.application.CDSApplicationUpdaterImpl"
use_softwareIdForAppName = true
[open_banking.dcr.jwks_retriever]
connection_timeout = 3000
read_timeout = 3000

[[open_banking.dcr.regulatory_issuers.iss]]
name = "cdr-register"

#Signature algorithm types that are allowed
#[[open_banking.signature_validation.allowed_algorithms.algorithms]]
#algorithm = "PS256"

[open_banking.sca.primaryauth]
name = "IdentifierExecutor"
display = "ob-identifier-first"

#[open_banking.sca.idp]
#name = ""

[open_banking.dcr.registration.grant_types]
allowed_values = ["authorization_code", "refresh_token", "client_credentials"]

[open_banking.dcr.registration.audience]
allowed_values = ["https://IS_HOSTNAME:9446/oauth2/token"]

[open_banking.dcr.registration.token_endpoint_authentication]
allowed_values = ["private_key_jwt"]

[open_banking.dcr.registration.response_types]
required = true
allowed_values = ["code id_token"]

[open_banking.dcr.registration.callback_uris]
allowed_values = ["https://www.google.com/redirects/redirect1",
    "https://www.google.com/redirects/redirect2"]

[open_banking.dcr.registration.application_type]
allowed_values = ["web"]

[open_banking.dcr.registration.id_token_encryption_response_alg]
required = true
allowed_values = ["RSA-OAEP", "RSA-OAEP-256"]

[open_banking.dcr.registration.id_token_encryption_response_enc]
required = true
allowed_values = ["A256GCM", "A128CBC-HS256"]

[open_banking.dcr.registration.token_endpoint_auth_signing_alg]
required = true

[open_banking.data_publishing]
enable = false
username="$ref{super_admin.username}@carbon.super"
password="$ref{super_admin.password}"
server_url = "{tcp://BI_HOSTNAME:7612}"
#auth_url = "{ssl://BI_HOSTNAME:7612}"
protocol = "Thrift"
pool_size = 10
queue_size = 32768
worker_thread_count = 10
pool_wait_time_Ms = 60000
auth_data_publisher = "com.wso2.openbanking.accelerator.authentication.data.publisher.extension.DefaultAuthDataPublisher"

[open_banking.data_publishing.thrift]
publishing_timeout = 2000
#data streams and their attributes with the priority order
[[open_banking.data_publishing.thrift.stream]]
name="AuthenticationInputStream"
[[open_banking.data_publishing.thrift.stream.attributes]]
name="userId"
priority=1
[[open_banking.data_publishing.thrift.stream.attributes]]
name="authenticationStep"
priority=2
[[open_banking.data_publishing.thrift.stream.attributes]]
name="authenticationStatus"
priority=3
required=true
[[open_banking.data_publishing.thrift.stream.attributes]]
name="authenticationApproach"
priority=4
required=true
[[open_banking.data_publishing.thrift.stream.attributes]]
name="psuChannel"
priority=5
[[open_banking.data_publishing.thrift.stream.attributes]]
name="timestamp"
priority=6
required=true
type="long"

[[open_banking.data_publishing.thrift.stream]]
name="AccessTokenInputStream"
[[open_banking.data_publishing.thrift.stream.attributes]]
name="accessTokenID"
priority=1

#================custom filters and filter-mappings==============
[[tomcat.filter]]
name = "TokenFilter"
class = "com.wso2.openbanking.accelerator.identity.token.TokenFilter"

[[tomcat.filter_mapping]]
name = "TokenFilter"
url_pattern = "/token"

#================consent management==============
[[open_banking.consent.authorize_steps.retrieve]]
class = "com.wso2.openbanking.accelerator.consent.extensions.authorize.impl.NonRegulatoryConsentStep"
priority = 1

[[open_banking.consent.authorize_steps.retrieve]]
class = "com.wso2.openbanking.cds.consent.extensions.authorize.impl.retrieval.CDSConsentRetrievalStep"
priority = 2

[[open_banking.consent.authorize_steps.retrieve]]
class = "com.wso2.openbanking.cds.consent.extensions.authorize.impl.retrieval.CDSDataClusterRetrievalStep"
priority = 3

[[open_banking.consent.authorize_steps.retrieve]]
class = "com.wso2.openbanking.cds.consent.extensions.authorize.impl.retrieval.CDSAccountListRetrievalStep"
priority = 4

[[open_banking.consent.authorize_steps.persist]]
class = "com.wso2.openbanking.cds.consent.extensions.authorize.impl.persist.CDSConsentPersistStep"
priority = 1

[open_banking.consent.manage]
handler="com.wso2.openbanking.accelerator.consent.extensions.manage.impl.DefaultConsentManageHandler"

[open_banking.consent.validation]
validator="com.wso2.openbanking.cds.consent.extensions.validate.CDSConsentValidator"

[open_banking.consent.validation.signature]
alias="wso2carbon"

[open_banking.consent.admin]
handler="com.wso2.openbanking.accelerator.consent.extensions.admin.impl.DefaultConsentAdminHandler"

[open_banking.identity.extensions]
request_object_validator="com.wso2.openbanking.cds.identity.auth.extensions.request.validator.CDSRequestObjectValidator"
response_type_handler="com.wso2.openbanking.cds.identity.auth.extensions.response.handler.CDSResponseTypeHandlerImpl"
claim_provider="com.wso2.openbanking.cds.identity.claims.CDSClaimProvider"
push_auth_request_validator="com.wso2.openbanking.cds.identity.push.auth.extension.request.validator.CDSPushAuthRequestValidator"

#=======================configs related to open-banking-cds.xml=====================

#[open_banking_cds.dcr]
#enable_uri_validation=true
#enable_hostname_validation=true
#enable_sector_identifier_uri_validation=true

#[open_banking_cds.consent_management]
#sharable_accounts_retrieve_endpoint="https://run.mocky.io/v3/49ea6f7b-a7d7-44db-956a-c9de2a072e41"
#validate_account_id_on_retrieval=true


#[open_banking_cds.customer_details]
#enable=false
#customer_details_retrieval_endpoint="https://run.mocky.io/v3/602f170e-55ff-49cb-8d6a-e0c3a8d7a5cc"
