blank_issues_enabled: false
contact_links:
  - name: Report an issue
    url: https://github.com/wso2-enterprise/financial-open-banking/issues/new
    about: Issue creation for this component is done in the financial-open-banking main  repo. Click "Open" to continue.
