name: Check PR Label

on:
  pull_request:
    branches:
     - 'main'
    types:
      - opened
      - labeled
      - unlabeled

jobs:

  Build-label-check:

    runs-on: ubuntu-latest

    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Ready-to-Build') || join(github.event.pull_request.labels) == '' }}
    steps:
      - name: Fail if PR is not yet built
        run: |
          echo "This PR needs to be built before merging to the repository."
          exit 1
